### ISSUE TITLE
Installing (on Ubuntu 20.04)

### ISSUE THREAD

**Issue by drohen** [ijc8/aleatora#2]
Just some issues with scipy:

- SciPy is [recommended to be installed via conda](https://www.scipy.org/install.html), not sure if this is something you want to look in to as it likely makes set up easier.
- I didn't use conda, as I wanted to test the process without it and found I needed to also run:
   - `sudo apt install libatlas-base-dev` ([ref](https://www.scipy.org/install.html))
   - `sudo apt-get install gfortran` ([ref](https://github.com/scipy/scipy/issues/9005#issuecomment-623528512))

- Also, pypy3 is installed as such: `sudo apt install pypy3 pypy3-dev`

Additionally, I'm getting some underruns with ALSA, actually, basically non-stop underruns, so I'm going to figure out how to fix that on my computer and will update in this issue if relevant.

**Comment by ijc8** [comment]
Thanks for the feedback on the installation process.

Good point about the non-Python SciPy dependencies; I neglected to mention them.
(I suppose conda takes care of them automatically, which is part of the appeal.)
Now that I think about it, the code is only using a single function from SciPy (`scipy.signal.resample`), so my inclination is to just get rid of the dependency and simplify the installation process.

Good point about PyPy, too. It's not a requirement (plenty should be doable in CPython without underruns), but it's nice to have. I'll mention its installation in the docs.

Regarding the underruns: oh no! That shouldn't happen.
A few checks that might help with debugging:
- What version of CPython/PyPy was this in?
- What is the output of `query_devices()`?
- What is the output of `_ = list(profile('osc', osc(440)[:10.0])); profile.dump()`?
- Do you get underruns with any of the following?
  - `run(osc(440))`
  - `f = freeze(osc(440)[:5.0]); play(f)`
  - `play(silence)`

You might also try the latest Aleatora, which is considerably faster than the version in PyPI. You can get it by cloning the repository and then doing `pip install -e <path to repo>`. (I'll add this to the docs, too.)

**Comment by drohen** [comment]
```
» python --version     
Python 3.6.9 (7.3.1+dfsg-4, Apr 22 2020, 05:15:29)
[PyPy 7.3.1 with GCC 9.3.0]
```

```
>>>> query_devices()
   0 HDA Intel PCH: HDMI 0 (hw:0,3), ALSA (0 in, 8 out)
   1 HDA Intel PCH: HDMI 1 (hw:0,7), ALSA (0 in, 8 out)
   2 HDA Intel PCH: HDMI 2 (hw:0,8), ALSA (0 in, 8 out)
   3 HDA Intel PCH: HDMI 3 (hw:0,9), ALSA (0 in, 8 out)
   4 HDA Intel PCH: HDMI 4 (hw:0,10), ALSA (0 in, 8 out)
   5 HDA Intel PCH: HDMI 5 (hw:0,11), ALSA (0 in, 8 out)
   6 HDA Intel PCH: HDMI 6 (hw:0,12), ALSA (0 in, 8 out)
   7 USB-C Triple-4K Dock: Audio (hw:1,0), ALSA (2 in, 6 out)
   8 hdmi, ALSA (0 in, 8 out)
   9 pulse, ALSA (32 in, 32 out)
* 10 default, ALSA (32 in, 32 out)
```

```
with BT headphones:
>>>> _ = list(profile('osc', osc(440)[:10.0])); profile.dump()
Real-time budget: 22.676us per sample
osc: 441001 calls (1 ending)
     0.173us avg | 0.076s total | 0.76% of budget

with computer speakers:
>>>> _ = list(profile('osc', osc(440)[:10.0])); profile.dump()
Real-time budget: 22.676us per sample
osc: 882002 calls (2 endings)
     0.149us avg | 0.131s total | 0.66% of budget
```

I get an underrun at the start of `run(osc(440))` which is odd because yesterday I got a crazy amount of underruns, but also I've since restarted my computer so there could be a reason there I guess.

Works fine now I guess, also tried with new version, similar results. However, the examples didn't work with the new version, so I retried the PyPI version (0.1.0) and the examples work as expected.

**Comment by ijc8** [comment]
Thanks for the details; glad the issue seems to be resolved. There may be some underruns when the audio device is first set up (when `run()` is called, or the first time `play()` is called), but they should not persist.

The `main` branch points to the latest code; this will become 0.2.0 when I release it on PyPI. As it's still in development, there may be some things that have broken (like examples) as the API has changed. Pardon the dust - and thanks bringing it to my attention.

I've updated the installation instructions, removed the dependency on SciPy, and updates some examples (`csick`, `layers`, and `phase`); others will get updated or replaced when I get around to writing up a tutorial.
